# Generated by Django 5.1.4 on 2024-12-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ToDoList',
            new_name='todolist',
        ),
    ]
